name: Build je2be-desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Verify CMake installation
      run: cmake --version

    - name: Configure CMake
      run: cmake -S . -B Builds

    - name: Build the project
      run: cmake --build Builds --target je2be-desktop --config Release --parallel

    - name: Archive the build output
      uses: actions/upload-artifact@v3
      with:
        name: je2be-desktop
        path: Builds/je2be-desktop_artifacts/Release/je2be.exe
